const axios = require('axios');

const data = [
    {
        major: 5,
        minor: 38,
        time: '2026-02-20T14:06:25+08:00',
        netUser: '',
        remoteHostAddr: '0.0.0.0',
        cardNo: '',
        cardType: 1,
        whiteListNo: 0,
        reportChannel: 0,
        cardReaderKind: 0,
        cardReaderNo: 1,
        doorNo: 1,
        verifyNo: 0,
        alarmInNo: 0,
        alarmOutNo: 0,
        caseSensorNo: 0,
        RS485No: 0,
        multiCardGroupNo: 0,
        accessChannel: 0,
        deviceNo: 0,
        distractControlNo: 0,
        employeeNoString: '1',
        localControllerID: 0,
        InternetAccess: 0,
        type: 0,
        MACAddr: '',
        swipeCardType: 0,
        serialNo: 197,
        userType: 'normal',
        attendanceStatus: 'undefined',
        statusValue: 0,
        userName: 'Leandro'
    },
    {
        major: 5,
        minor: 38,
        time: '2026-02-20T14:21:18+08:00',
        netUser: '',
        remoteHostAddr: '0.0.0.0',
        cardNo: '',
        cardType: 1,
        whiteListNo: 0,
        reportChannel: 0,
        cardReaderKind: 0,
        cardReaderNo: 1,
        doorNo: 1,
        verifyNo: 0,
        alarmInNo: 0,
        alarmOutNo: 0,
        caseSensorNo: 0,
        RS485No: 0,
        multiCardGroupNo: 0,
        accessChannel: 0,
        deviceNo: 0,
        distractControlNo: 0,
        employeeNoString: '00000001',
        localControllerID: 0,
        InternetAccess: 0,
        type: 0,
        MACAddr: '',
        swipeCardType: 0,
        serialNo: 264,
        userType: 'normal',
        attendanceStatus: 'undefined',
        statusValue: 0,
        userName: '1130264365 - Jean Correa'
    },
    {
        major: 5,
        minor: 38,
        time: '2026-02-20T14:40:55+08:00',
        netUser: '',
        remoteHostAddr: '0.0.0.0',
        cardNo: '',
        cardType: 1,
        whiteListNo: 0,
        reportChannel: 0,
        cardReaderKind: 0,
        cardReaderNo: 1,
        doorNo: 1,
        verifyNo: 0,
        alarmInNo: 0,
        alarmOutNo: 0,
        caseSensorNo: 0,
        RS485No: 0,
        multiCardGroupNo: 0,
        accessChannel: 0,
        deviceNo: 0,
        distractControlNo: 0,
        employeeNoString: '00000001',
        localControllerID: 0,
        InternetAccess: 0,
        type: 0,
        MACAddr: '',
        swipeCardType: 0,
        serialNo: 309,
        userType: 'normal',
        attendanceStatus: 'undefined',
        statusValue: 0,
        userName: '1130264365 - Jean Correa'
    },
    {
        major: 5,
        minor: 38,
        time: '2026-02-20T14:44:32+08:00',
        netUser: '',
        remoteHostAddr: '0.0.0.0',
        cardNo: '',
        cardType: 1,
        whiteListNo: 0,
        reportChannel: 0,
        cardReaderKind: 0,
        cardReaderNo: 1,
        doorNo: 1,
        verifyNo: 0,
        alarmInNo: 0,
        alarmOutNo: 0,
        caseSensorNo: 0,
        RS485No: 0,
        multiCardGroupNo: 0,
        accessChannel: 0,
        deviceNo: 0,
        distractControlNo: 0,
        employeeNoString: '00000001',
        localControllerID: 0,
        InternetAccess: 0,
        type: 0,
        MACAddr: '',
        swipeCardType: 0,
        serialNo: 316,
        userType: 'normal',
        attendanceStatus: 'undefined',
        statusValue: 0,
        userName: '1130264365 - Jean Correa'
    },
    {
        major: 5,
        minor: 38,
        time: '2026-02-20T15:43:39+08:00',
        netUser: '',
        remoteHostAddr: '0.0.0.0',
        cardNo: '',
        cardType: 1,
        whiteListNo: 0,
        reportChannel: 0,
        cardReaderKind: 0,
        cardReaderNo: 1,
        doorNo: 1,
        verifyNo: 0,
        alarmInNo: 0,
        alarmOutNo: 0,
        caseSensorNo: 0,
        RS485No: 0,
        multiCardGroupNo: 0,
        accessChannel: 0,
        deviceNo: 0,
        distractControlNo: 0,
        employeeNoString: '00000001',
        localControllerID: 0,
        InternetAccess: 0,
        type: 0,
        MACAddr: '',
        swipeCardType: 0,
        serialNo: 386,
        userType: 'normal',
        attendanceStatus: 'undefined',
        statusValue: 0,
        userName: '1130264365 - Jean Correa'
    },
    {
        major: 5,
        minor: 38,
        time: '2026-02-20T15:50:32+08:00',
        netUser: '',
        remoteHostAddr: '0.0.0.0',
        cardNo: '',
        cardType: 1,
        whiteListNo: 0,
        reportChannel: 0,
        cardReaderKind: 0,
        cardReaderNo: 1,
        doorNo: 1,
        verifyNo: 0,
        alarmInNo: 0,
        alarmOutNo: 0,
        caseSensorNo: 0,
        RS485No: 0,
        multiCardGroupNo: 0,
        accessChannel: 0,
        deviceNo: 0,
        distractControlNo: 0,
        employeeNoString: '00000001',
        localControllerID: 0,
        InternetAccess: 0,
        type: 0,
        MACAddr: '',
        swipeCardType: 0,
        serialNo: 395,
        userType: 'normal',
        attendanceStatus: 'undefined',
        statusValue: 0,
        userName: '1130264365 - Jean Correa'
    },
    {
        major: 5,
        minor: 38,
        time: '2026-02-20T16:04:56+08:00',
        netUser: '',
        remoteHostAddr: '0.0.0.0',
        cardNo: '',
        cardType: 1,
        whiteListNo: 0,
        reportChannel: 0,
        cardReaderKind: 0,
        cardReaderNo: 1,
        doorNo: 1,
        verifyNo: 0,
        alarmInNo: 0,
        alarmOutNo: 0,
        caseSensorNo: 0,
        RS485No: 0,
        multiCardGroupNo: 0,
        accessChannel: 0,
        deviceNo: 0,
        distractControlNo: 0,
        employeeNoString: '1',
        localControllerID: 0,
        InternetAccess: 0,
        type: 0,
        MACAddr: '',
        swipeCardType: 0,
        serialNo: 403,
        userType: 'normal',
        attendanceStatus: 'undefined',
        statusValue: 0,
        userName: 'Leandro'
    },
    {
        major: 5,
        minor: 153,
        time: '2026-02-20T17:03:31+08:00',
        netUser: '',
        remoteHostAddr: '0.0.0.0',
        cardNo: '',
        cardType: 6,
        whiteListNo: 0,
        reportChannel: 0,
        cardReaderKind: 0,
        cardReaderNo: 1,
        doorNo: 1,
        verifyNo: 0,
        alarmInNo: 0,
        alarmOutNo: 0,
        caseSensorNo: 0,
        RS485No: 0,
        multiCardGroupNo: 0,
        accessChannel: 0,
        deviceNo: 0,
        distractControlNo: 0,
        employeeNoString: '00000001',
        localControllerID: 0,
        InternetAccess: 0,
        type: 0,
        MACAddr: '',
        swipeCardType: 0,
        serialNo: 451,
        userType: 'normal',
        attendanceStatus: 'undefined',
        statusValue: 0,
        userName: '1130264365 - Jean Correa'
    },
    {
        major: 5,
        minor: 153,
        time: '2026-02-20T17:10:18+08:00',
        netUser: '',
        remoteHostAddr: '0.0.0.0',
        cardNo: '',
        cardType: 6,
        whiteListNo: 0,
        reportChannel: 0,
        cardReaderKind: 0,
        cardReaderNo: 1,
        doorNo: 1,
        verifyNo: 0,
        alarmInNo: 0,
        alarmOutNo: 0,
        caseSensorNo: 0,
        RS485No: 0,
        multiCardGroupNo: 0,
        accessChannel: 0,
        deviceNo: 0,
        distractControlNo: 0,
        employeeNoString: '00000001',
        localControllerID: 0,
        InternetAccess: 0,
        type: 0,
        MACAddr: '',
        swipeCardType: 0,
        serialNo: 462,
        userType: 'normal',
        attendanceStatus: 'undefined',
        statusValue: 0,
        userName: '1130264365 - Jean Correa'
    },
    {
        major: 5,
        minor: 153,
        time: '2026-02-20T17:26:37+08:00',
        netUser: '',
        remoteHostAddr: '0.0.0.0',
        cardNo: '',
        cardType: 6,
        whiteListNo: 0,
        reportChannel: 0,
        cardReaderKind: 0,
        cardReaderNo: 1,
        doorNo: 1,
        verifyNo: 0,
        alarmInNo: 0,
        alarmOutNo: 0,
        caseSensorNo: 0,
        RS485No: 0,
        multiCardGroupNo: 0,
        accessChannel: 0,
        deviceNo: 0,
        distractControlNo: 0,
        employeeNoString: '00000001',
        localControllerID: 0,
        InternetAccess: 0,
        type: 0,
        MACAddr: '',
        swipeCardType: 0,
        serialNo: 477,
        userType: 'normal',
        attendanceStatus: 'undefined',
        statusValue: 0,
        userName: '1130264365 - Jean Correa'
    }
];

const SYNC_TOKEN = 'HikvisionSecretToken2026';
const URL = 'http://localhost:3000/api/sync/push';

async function test() {
    try {
        console.log('Enviando data al endpoint PUSH...');
        const response = await axios.post(URL, data, {
            headers: {
                'x-sync-token': SYNC_TOKEN,
                'Content-Type': 'application/json'
            }
        });
        console.log('Respuesta del servidor:', response.data);
    } catch (error) {
        console.error('Error en el test:', error.response ? error.response.data : error.message);
    }
}

test();
